// Feature Flags
export const FEATURES = {
  ENABLE_MESSENGER: true,
  ENABLE_ANALYTICS: true,
  ENABLE_NOTIFICATIONS: true,
  ENABLE_LEADS_MANAGEMENT: true,
};

export const VALIDATION_RULES = {
  PASSWORD_MIN_LENGTH: 8,
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 50,
  DESCRIPTION_MAX_LENGTH: 1000,
  TEMPLATE_MAX_LENGTH: 500,
};

export const CACHE_CONFIG = {
  TEMPLATES_TTL: 5 * 60 * 1000,
  CONFIG_TTL: 10 * 60 * 1000,
  LEADS_TTL: 3 * 60 * 1000,
};
