// UI Configuration
export const UI_CONFIG = {
  TOAST_DURATION: 3000,
  MODAL_ANIMATION_DURATION: 300,
  DEBOUNCE_DELAY: 500,
  PAGINATION_DEFAULT_SIZE: 20,
};

export const DATE_FORMATS = {
  SHORT_DATE: 'DD/MM/YYYY',
  LONG_DATE: 'DD MMMM YYYY',
  TIME_24H: 'HH:mm',
  DATETIME: 'DD/MM/YYYY HH:mm',
};
